version: '3.5'

services:
  spark-master:
    image: natbusa/pyspark-notebook:2.4.4-hadoop-3.2.0
    command: /opt/spark/sbin/start-master.sh
    user: root
    environment:
      SPARK_NO_DAEMONIZE: "true"
    ports:
    - 8080:8080
    networks:
    - databox

  spark-worker1:
    image: natbusa/pyspark-notebook:2.4.4-hadoop-3.2.0
    command: /opt/spark/sbin/start-slave.sh spark://spark-master:7077
    user: root
    depends_on:
    - spark-master
    environment:
      SPARK_NO_DAEMONIZE: "true"
    networks:
    - databox

  spark-worker2:
    image: natbusa/pyspark-notebook:2.4.4-hadoop-3.2.0
    command: /opt/spark/sbin/start-slave.sh spark://spark-master:7077
    user: root
    depends_on:
    - spark-master
    environment:
      SPARK_NO_DAEMONIZE: "true"
    networks:
    - databox

networks:
  databox:
    external: true
