version: '3.5'

services:
  jupyter:
    image: databox/pyspark-notebook:2.4.4-hadoop-3.2.1
    command: ['start-notebook.sh', '--NotebookApp.token=""']
    user: root
    environment:
      JUPYTER_ENABLE_LAB: "true"
      DEMO_PATH:  /home/jovyan/work/${DEMO_NAME}
      CHOWN_EXTRA: "/home/jovyan/.ivy2,/home/jovyan/develop"
      GRANT_SUDO: 1
    ports:
    - 8888:8888
    networks:
    - databox
    volumes:
    - ./startup.d:/usr/local/bin/before-notebook.d:ro
    - ${DEMO_DIR}:/home/jovyan/work/${DEMO_NAME}
    - develop:/home/jovyan/develop

networks:
  databox:
    external: true

volumes:
  develop:
