version: '3.5'

services:
  jupyter:
    image: datalabframework-demos/pyspark-notebook:2.4.0-hadoop-3.1.1
    command: ['start-notebook.sh', '--NotebookApp.token=""']
    user: root
    environment:
      JUPYTER_ENABLE_LAB: "true"
      DEMO_PATH:  /home/jovyan/work/${DEMO_NAME}
      CHOWN_EXTRA: "/home/jovyan/.ivy2,/home/jovyan/develop"
      GRANT_SUDO: 1
    ports:
    - 8888:8888
    networks:
    - datalabframework
    volumes:
    - ./startup.d:/usr/local/bin/before-notebook.d:ro
    - ./config:/opt/spark/conf:ro
    - ${DEMO_DIR}:/home/jovyan/work/${DEMO_NAME}
    - develop:/home/jovyan/develop
    - ivy2:/home/jovyan/.ivy2:cached

networks:
  datalabframework:
    external: true

volumes:
  ivy2:
  develop:
